# Local development profile

# Frontend URL
frontend.url=http://localhost:5173

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/everage
spring.datasource.username=postgres
spring.datasource.password=postgres

# Flyway
spring.flyway.enabled=true

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.com.everage.eshop=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Swagger
springdoc.swagger-ui.enabled=true