# Production profile

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

# Logging (JSON format)
logging.level.root=INFO
logging.level.com.everage.eshop=INFO

# Actuator - ???????????? ? ?????
management.endpoints.web.exposure.include=health,info