server.port=8080
# Server URL for Swagger (will be overridden in prod)
server.url=${SERVER_URL:http://localhost:8080}

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/everage
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.swagger-ui.enabled=true
# Important for CORS if UI is on another domain
springdoc.api-docs.swagger-ui.csrf.enabled=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always