server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]

    relabel_configs:
      # Extracting the container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      # Extracting the application label
      - source_labels: ['__meta_docker_container_label_application']
        target_label: 'application'

      # Add stream (stdout/stderr)
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

    # Pipeline for processing JSON logs
    pipeline_stages:
      # Parse JSON if its possible
      - json:
          expressions:
            timestamp: '"@timestamp"'
            level: level
            logger: logger
            message: message
            thread: thread
            application: application

      # Set timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano

      # Adding labels from JSON
      - labels:
          level:
          logger:
          application:

      - output:
          source: message